In [1]:
import pandas as pd

df = pd.read_csv('restaurant_temp.csv')

In [9]:
# 조건 적용: "Processed"가 "Yes"이고 "메뉴"가 빈 리스트인 경우
mask = (df["Processed"] == "Yes") & (df["메뉴"] == "[]")

# "Processed"와 "메뉴" 값을 빈 문자열로 변경
df.loc[mask, ["Processed", "메뉴"]] = ""

In [11]:
df

,지번주소,사업장명,Processed,메뉴
0,서울특별시 마포구 서교동 399-9,라운지목화 합정관,Yes,"[['아보카도크림새우', 19900], ['깐풍기', 18500], ['사천가지튀김..."
1,서울특별시 마포구 서교동 378-10 H 스퀘어,탭샵바 합정점,Yes,"[['루꼴라 치즈 떡볶이', 9900]]"
2,서울특별시 마포구 서교동 333-37,연남골목냉면,Yes,"[['명태회냉면', 10000], ['물냉면', 8000], ['비빔냉면', 800..."
3,서울특별시 마포구 서교동 396-27,유아하,Yes,"[['유아하 할머니의 훠궈', 32900], ['우삼겹 후추탕', 25000], [..."
4,서울특별시 마포구 서교동 347-14,증증일상,Yes,"[['꽌탕바오(육즙 샤오롱바오)', 7300], ['성젠바오(육즙 군만두)', 70..."
...,...,...,...,...
600,서울특별시 마포구 합정동 437-31 1층일부,넌덕,NaN,NaN
601,서울특별시 마포구 합정동 410-2,족발애감동,Yes,"[['냉채족발', 37000], ['돼지김치찌개', 7000], ['매운 족 (대)..."
602,서울특별시 마포구 합정동 375-18,이키,Yes,"[['제철사시미', 30000], ['완도김파스타', 16000], ['멘치까스',..."
603,서울특별시 마포구 합정동 472 마포 한강 푸르지오,이가네 양꼬치 양갈비,NaN,NaN
604,서울특별시 마포구 합정동 377-32 동원빌딩,같이양조장,,

In [12]:
df.to_csv("restaurant_temp.csv", index=False, encoding="utf-8")